/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeGraph {
  constructor(graphJson: string)
  get nodeCount(): number
  get edgeCount(): number
  canonicalJson(): string
  nodeJson(id: string): string | null
  outgoingJson(id: string): string
  incomingJson(id: string): string
  bfs(start: string): Array<string>
  shortestPath(source: string, target: string): Array<string> | null
  stronglyConnectedComponentsJson(): string
  topologicalSort(): Array<string> | null
  hasCycle(): boolean
  pageRankJson(damping?: number | undefined | null, iterations?: number | undefined | null): string
  toDot(): string
}
